export const proDrivers = [
  { competitorId: "pro-10", competitorName: "JANUŠAUSKAITĖ Sandra", nationality: "LTU", car: "BMW F22", competitionClass: "PRO", competitionNumbers: "10" },
  { competitorId: "pro-14", competitorName: "FABISIAK Dariusz", nationality: "POL", car: "Nissan 200SX S14", competitionClass: "PRO", competitionNumbers: "14" },
  { competitorId: "pro-21", competitorName: "WARTAŁOWICZ Marek", nationality: "POL", car: "Nissan PS13", competitionClass: "PRO", competitionNumbers: "21" },
  { competitorId: "pro-25", competitorName: "MLADENOV Samuel", nationality: "SVK", car: "BMW E92", competitionClass: "PRO", competitionNumbers: "25" },
  { competitorId: "pro-27", competitorName: "FIJAŁ Aleksandra", nationality: "POL", car: "Nissan S13 200SX", competitionClass: "PRO", competitionNumbers: "27" },
  { competitorId: "pro-28", competitorName: "MERILOO Graig", nationality: "EST", car: "BMW Presision next gen", competitionClass: "PRO", competitionNumbers: "28" },
  { competitorId: "pro-31", competitorName: "WAAGAARD Joachim", nationality: "NOR", car: "BMW M4", competitionClass: "PRO", competitionNumbers: "31" },
  { competitorId: "pro-46", competitorName: "KUR Dominik", nationality: "POL", car: "Opel GT", competitionClass: "PRO", competitionNumbers: "46" },
  { competitorId: "pro-52", competitorName: "HEIDRICH Tim", nationality: "POL", car: "Mercedes Benz", competitionClass: "PRO", competitionNumbers: "52" },
  { competitorId: "pro-58", competitorName: "OLEJNIK Jacek", nationality: "POL", car: "BMW E92", competitionClass: "PRO", competitionNumbers: "58" },
  { competitorId: "pro-63", competitorName: "ZAKRZEWSKI Mikołaj", nationality: "POL", car: "Nissan Silvia S15", competitionClass: "PRO", competitionNumbers: "63" },
  { competitorId: "pro-66", competitorName: "STOLARSKI Bartosz", nationality: "POL", car: "Nissan 200SX S15", competitionClass: "PRO", competitionNumbers: "66" },
  { competitorId: "pro-68", competitorName: "ERLANDSSON Christian", nationality: "SWE", car: "Subaru BRZ", competitionClass: "PRO", competitionNumbers: "68" },
  { competitorId: "pro-69", competitorName: "PILARCZYK Karolina", nationality: "POL", car: "Nissan 200SX S15", competitionClass: "PRO", competitionNumbers: "69" },
  { competitorId: "pro-71", competitorName: "JARKIEWICZ Maciej", nationality: "POL", car: "Nissan S14", competitionClass: "PRO", competitionNumbers: "71" },
  { competitorId: "pro-75", competitorName: "UTASI Péter", nationality: "HUN", car: "BMW F22", competitionClass: "PRO", competitionNumbers: "75" },
  { competitorId: "pro-78", competitorName: "KOZŁOWSKI Piotr", nationality: "POL", car: "Nissan Silvia S15", competitionClass: "PRO", competitionNumbers: "78" },
  { competitorId: "pro-82", competitorName: "STAŃCZAK Piotr", nationality: "POL", car: "BMW E82", competitionClass: "PRO", competitionNumbers: "82" },
  { competitorId: "pro-86", competitorName: "PRZYGOŃSKI Jakub", nationality: "POL", car: "Toyota GR86", competitionClass: "PRO", competitionNumbers: "86" },
  { competitorId: "pro-93", competitorName: "FOJTÍK Michal", nationality: "CZE", car: "BMW M3 E46 V8 Turbo", competitionClass: "PRO", competitionNumbers: "93" },
  { competitorId: "pro-94", competitorName: "ALHARBALI URIAS Nasser", nationality: "SLV", car: "Nissan S13", competitionClass: "PRO", competitionNumbers: "94" },
  { competitorId: "pro-96", competitorName: "SALMRE Kristjan", nationality: "EST", car: "BMW 1", competitionClass: "PRO", competitionNumbers: "96" },
  { competitorId: "pro-98", competitorName: "WROBEL Kevin", nationality: "POL", car: "BMW E36", competitionClass: "PRO", competitionNumbers: "98" },
  { competitorId: "pro-111", competitorName: "JÓŹWIAK Krzysztof", nationality: "POL", car: "BMW F22", competitionClass: "PRO", competitionNumbers: "111" },
  { competitorId: "pro-130", competitorName: "SHEVELOV Valerii", nationality: "UKR", car: "Nissan S13", competitionClass: "PRO", competitionNumbers: "130" },
  { competitorId: "pro-155", competitorName: "MICHALCZUK Orest", nationality: "POL", car: "Nissan 200SX", competitionClass: "PRO", competitionNumbers: "155" },
  { competitorId: "pro-177", competitorName: "DOROZIŃSKI Fabian", nationality: "ISL", car: "Nissan S14 200SX", competitionClass: "PRO", competitionNumbers: "177" },
  { competitorId: "pro-201", competitorName: "DRUZSIN Matyas", nationality: "HUN", car: "BMW M104 Turbo", competitionClass: "PRO", competitionNumbers: "201" },
  { competitorId: "pro-212", competitorName: "WETTEMARK Viktor", nationality: "SWE", car: "Nissan S14.9", competitionClass: "PRO", competitionNumbers: "212" },
  { competitorId: "pro-225", competitorName: "KRÓL Jakub", nationality: "POL", car: "Nissan 200SX S14", competitionClass: "PRO", competitionNumbers: "225" },
  { competitorId: "pro-234", competitorName: "NEJMAN Marcin", nationality: "POL", car: "BMW F22", competitionClass: "PRO", competitionNumbers: "234" },
  { competitorId: "pro-245", competitorName: "HORECKI Kamil", nationality: "POL", car: "BMW E82", competitionClass: "PRO", competitionNumbers: "245" },
  { competitorId: "pro-254", competitorName: "KADEŘÁBEK Zdeněk", nationality: "CZE", car: "BMW E46", competitionClass: "PRO", competitionNumbers: "254" },
  { competitorId: "pro-258", competitorName: "ANDERSSON Viktor", nationality: "SWE", car: "Toyota GT86", competitionClass: "PRO", competitionNumbers: "258" },
  { competitorId: "pro-277", competitorName: "SUSKI Mateusz", nationality: "POL", car: "Toyota Supra", competitionClass: "PRO", competitionNumbers: "277" },
  { competitorId: "pro-303", competitorName: "WILCZEK Łukasz", nationality: "POL", car: "BMW M3 E46", competitionClass: "PRO", competitionNumbers: "303" },
  { competitorId: "pro-333", competitorName: "HAVRYLENKO Artur", nationality: "UKR", car: "Toyota GT86", competitionClass: "PRO", competitionNumbers: "333" },
  { competitorId: "pro-383", competitorName: "BERTRAND Denis", nationality: "BEL", car: "BMW E46", competitionClass: "PRO", competitionNumbers: "383" },
  { competitorId: "pro-420", competitorName: "HAMWY Michel", nationality: "SWE", car: "Nissan S14", competitionClass: "PRO", competitionNumbers: "420" },
  { competitorId: "pro-564", competitorName: "HUDECEK Pavel", nationality: "CZE", car: "Nissan", competitionClass: "PRO", competitionNumbers: "564" },
  { competitorId: "pro-595", competitorName: "KONEČNÝ Jan", nationality: "CZE", car: "BME E36", competitionClass: "PRO", competitionNumbers: "595" },
  { competitorId: "pro-666", competitorName: "FIJAŁ Mateusz", nationality: "POL", car: "Toyota GT86", competitionClass: "PRO", competitionNumbers: "666" },
  { competitorId: "pro-713", competitorName: "HOMAN Zsolt", nationality: "HUN", car: "Nissan S13", competitionClass: "PRO", competitionNumbers: "713" },
  { competitorId: "pro-717", competitorName: "ANDREASEN Mads", nationality: "DNK", car: "BMW M3", competitionClass: "PRO", competitionNumbers: "717" },
  { competitorId: "pro-744", competitorName: "MAGYAR Tamás", nationality: "HUN", car: "Mercedes E190", competitionClass: "PRO", competitionNumbers: "744" },
  { competitorId: "pro-772", competitorName: "PAWLONKA Krzysztof", nationality: "POL", car: "Nissan S15", competitionClass: "PRO", competitionNumbers: "772" },
  { competitorId: "pro-775", competitorName: "KOSZYCARZ Krzysztof", nationality: "POL", car: "BMW F22", competitionClass: "PRO", competitionNumbers: "775" },
  { competitorId: "pro-850", competitorName: "REICHERT Michal", nationality: "CZE", car: "BMW E36", competitionClass: "PRO", competitionNumbers: "850" },
  { competitorId: "pro-919", competitorName: "TASIEMSKI Łukasz", nationality: "POL", car: "Nissan 200SX", competitionClass: "PRO", competitionNumbers: "919" },
  { competitorId: "pro-999", competitorName: "SOUHRADA Lukáš", nationality: "CZE", car: "BMW E92", competitionClass: "PRO", competitionNumbers: "999" }
];
